export default {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL: "GET_PRODUCTS_FAIL",
  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAIL: "GET_PRODUCT_FAIL",
  GET_EXTENDED_PRODUCT: "GET_EXTENDED_PRODUCT",
  GET_EXTENDED_PRODUCT_SUCCESS: "GET_EXTENDED_PRODUCT_SUCCESS",
  GET_EXTENDED_PRODUCT_FAIL: "ACTIONS.GET_EXTENDED_PRODUCT_FAIL",

  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  FILTER_PRODUCTS_SUCCESS: "FILTER_PRODUCTS_SUCCESS",
  FILTER_PRODUCTS_FAIL: "FILTER_PRODUCTS_FAIL",

  SORT_PRODUCTS: "SORT_PRODUCTS",
  SORT_PRODUCTS_SUCCESS: "SORT_PRODUCTS_SUCCESS",
  SORT_PRODUCTS_FAIL: "SORT_PRODUCTS_FAIL",

  RESET_FILTERED_PRODUCTS: "RESET_FILTERED_PRODUCTS",

  GET_SELLERS: "GET_SELLERS",
  GET_SELLERS_SUCCESS: "GET_SELLERS_SUCCESS",
  GET_SELLERS_FAIL: "GET_SELLERS_FAIL",
  GET_SELLER: "GET_SELLER",
  GET_SELLER_SUCCESS: "GET_SELLER_SUCCESS",
  GET_SELLER_FAIL: "GET_SELLER_FAIL",
  GET_EXTENDED_SELLER: "GET_EXTENDED_SELLER",
  GET_EXTENDED_SELLER_SUCCESS: "GET_EXTENDED_SELLER_SUCCESS",
  GET_EXTENDED_SELLER_FAIL: "GET_EXTENDED_SELLER_FAIL",

  FILTER_SELLERS: "FILTER_SELLERS",
  FILTER_SELLERS_SUCCESS: "FILTER_SELLERS_SUCCESS",
  FILTER_SELLERS_FAIL: "FILTER_SELLERS_FAIL",

  SORT_SELLERS: "SORT_SELLERS",
  SORT_SELLERS_SUCCESS: "SORT_SELLERS_SUCCESS",
  SORT_SELLERS_FAIL: "SORT_SELLERS_FAIL",

  RESET_FILTERED_SELLERS: "RESET_FILTERED_SELLERS",

  GET_TOTALS: "GET_TOTALS",
  GET_TOTALS_SUCCESS: "GET_TOTALS_SUCCESS",
  GET_TOTALS_FAIL: "GET_TOTALS_FAIL",
}
